wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.5
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713753958.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.11.8
      5: 0.16.5
      8:
      - 4
      - 5
      13: darwin-arm64
